#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

alias l="ls"
alias ls="ls -hN --color=auto --group-directories-first"
alias ll="ls -lhN --color=auto --group-directories-first"
alias la="ls -lahN --color=auto --group-directories-first"
alias l.="ls -ahN --color=auto --group-directories-first | egrep '^\.'"
alias lg="ls -ahN --color=auto --group-directories-first | egrep '${1}'"

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Adding flags
alias cp='cp -i'
alias df='df -h'
alias free='free -m'

alias vifm='~/.config/vifm/scripts/vifmrun'
alias fm='cd "$(~/.config/vifm/scripts/vifmrun)"'

# Pacman
alias search-pac="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias remove-pac="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"

alias install="sudo pacman -S"
alias orphans="pacman -Qdtq"
alias update="sudo pacman -Syu"
alias uninstall="sudo pacman -Rns"

# youtube-dl
alias yta='youtube-dl --add-metadata --extract-audio --audio-format mp3 -o "./%(title)s.%(ext)s"'
alias ytv='youtube-dl -f "[height<=720]" -o "./%(title)s.%(ext)s"'

# Git
alias config='/usr/bin/git --git-dir=/home/blake/.dotfiles --work-tree=/home/blake' # Working with dotfiles

# FZF
# fd - cd to selected directory
fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

# fe [FUZZY PATTERN] - Open the selected file with the default editor
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
fe() {
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

alias dragon='dragon -a -x'
alias rmswp='rm ~/.local/share/nvim/swap/*'
alias myip='curl ipinfo.io/ip'
