#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

alias ls="ls -hN --color=auto --group-directories-first"
alias l="ls"
alias ll="ls -lhN --color=auto --group-directories-first"
alias la="ls -lahN --color=auto --group-directories-first"
alias l.="ls -ahN --color=auto --group-directories-first | egrep '^\.'"

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Adding flags
alias cp='cp -i'
alias df='df -h'
alias free='free -m'
alias vifm='~/.config/vifm/scripts/vifmrun'
alias fm='cd "$(~/.config/vifm/scripts/vifmrun)"'

alias search-pac="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias remove-pac="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"

# youtube-dl
alias yta-mp3='youtube-dl --add-metadata --extract-audio --audio-format mp3 -o "./%(title)s.%(ext)s"'
# alias yta-wav='youtube-dl --extract-audio --audio-format wav'
alias ytv-mp4='youtube-dl -f "[height<=720]" -o "./%(title)s.%(ext)s"'

# Git
alias config='/usr/bin/git --git-dir=/home/blake/.dotfiles --work-tree=/home/blake' # Working with dotfiles
